name: Generate CycloneDX BOM
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cyclonedx-gomod
        run: |
          curl -sL https://github.com/CycloneDX/cyclonedx-gomod/releases/download/v1.3.0/cyclonedx-gomod_1.3.0_linux_amd64.tar.gz | tar xz
          
      - name: Generate CycloneDX BOM
        run: |
            export FETCH_LICENSE=true
            cyclonedx-gomod generate -o sbom.xml
