name: MSFT_SBOM_TOOL
on: push       
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      - name: Install dependencies
        run: npm install
        
        env:
          DeleteManifestDirIfPresent: 'true'
      - name: Generate SBOM
        run: |
       
         curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
         chmod +x $RUNNER_TEMP/sbom-tool
         $RUNNER_TEMP/sbom-tool generate  -manifestDirPath ./ -b ~/.npm -bc . -pn npm -pv 1.0.0 -ps MyCompany -nsb https://sbom.mycompany.com -V Verbose | tee output.log
    
      - name: Save Sbom to new file 
        run: |    
           echo -n "$(cat './_manifest/spdx_2.2/manifest.spdx.json')" | jq '. + {"name": "${{github.actor}}"}' | jq '. + {"repo": "${{github.repositoryUrl}}"}' > sbom_file.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: sbom-json
          path: sbom_file.json 
     
      - name: Download SPDX tools
        run: wget https://github.com/CycloneDX/cyclonedx-cli/releases/download/v0.24.2/cyclonedx-linux-x64 && chmod +x cyclonedx-linux-x64
      - name: Convert SPDX to CycloneDX
        run: ./cyclonedx-linux-x64 convert --input-file sbom_file.json --output-file _manifest/manifest.CycloneDX.json --output-format json
      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: sbom-cyclonedx
          path: _manifest/manifest.CycloneDX.json 
