name: Generate CycloneDX BOM
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: sudo npm install -g @appthreat/cdxgen    
      - name: Generate CycloneDX BOM
        run: |
          cd $1
          export FETCH_LICENSE=true
          cdxgen -o sbom.json
 
