name: Generate SBOM
on: [push]

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
        
    - name: Download and install cyclonedx-gomod
      run: |
        curl -L https://github.com/CycloneDX/cyclonedx-gomod/releases/latest/download/cyclonedx-gomod_$(uname -s)_$(uname -m).tar.gz | tar xzv
        sudo mv cyclonedx-gomod /usr/local/bin/

    - name: Generate SBOM
      run: |
        cyclonedx-gomod mod -licenses -json -output sbom.json
