name: Generate CycloneDX BOM
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: npm install -g @cyclonedx/cdxgen@8.0.1       
      - name: Generate CycloneDX BOM
        run: |
           export FETCH_LICENSE=true
           cdxgen -r -o sbom.json
