name: Generate CycloneDX BOM
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download cyclonedx-gomod
      run: |
        curl -sL https://github.com/CycloneDX/cyclonedx-gomod/releases/download/v1.3.0/cyclonedx-gomod_1.3.0_linux_amd64.tar.gz | tar xz
        chmod +x cyclonedx-gomod
    - name: Generate CycloneDX BOM
      run: ./cyclonedx-gomod generate -o bom.xml
