name: Build SBOM and send to api.
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Create SBOM with CycloneDX
        id: sbom
        uses: CycloneDX/gh-gomod-generate-sbom@v1 
        with:
            output: './test.app.bom.json'
      - name: Save Sbom to new file 
        run: |    
           echo -n "$(cat './test.app.bom.json')" | jq '. + {"name": "${{github.actor}}"}' | jq '. + {"repo": "${{github.repositoryUrl}}"}' > sbom_file.json 
      - name: Call Api
        run: |  
          curl -k --request POST 'https://dt.cryptosoft.com:9443/api/v1/guest/sbom-github' \
          --header 'Content-Type: application/json' \
          --data  @sbom_file.json 
