name: Generate CycloneDX SBOM
on:
  push:
    branches: [ main ]
jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Download CycloneDX tool
        run: |
          curl -sL https://github.com/CycloneDX/cyclonedx-gomod/releases/download/v1.3.0/cyclonedx-gomod_1.3.0_linux_amd64.bom.json
          sudo mv cyclonedx-gomod /usr/local/bin/
      - name: Generate SBOM
        run: |
          cyclonedx-gomod mod -licenses -output sbom.xml
      - name: Upload SBOM
        uses: actions/upload-artifact@v2
        with:
          name: sbom
          path: sbom.json
