name: Generate CycloneDX BOM
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cyclonedx-gomod
        run: |
          curl -sL https://github.com/CycloneDX/cyclonedx-gomod/releases/download/v1.3.0/cyclonedx-gomod_1.3.0_linux_amd64.tar.gz | tar xz
          chmod +x cyclonedx-gomod
      - name: Generate CycloneDX BOM
        run: ./cyclonedx-gomod generate -o bom.xml
      - name: Upload CycloneDX BOM
        uses: actions/upload-artifact@v2
        with:
          name: bom.xml
          path: bom.xml
